### PR TITLE
Extensive README alterations

### PR DESCRIPTION
**Pull request by Solarstrike**

### CODE REVIEW

**Comment by Adaptivity** [comment]
I like README in the current format. Don't change it anymore.

**Comment by Solarstrike** [comment]
Why?

**Comment by Solarstrike** [comment]
@Adaptivity Why??

**Comment by Adaptivity** [comment]
It's just a readme file... it's a simple thing... it's already explains everything in a simple way. Just forget about it.

**Comment by Solarstrike** [comment]
What about grammatical errors?

**Comment by Solarstrike** [comment]
Ah, screw it.

**Comment by Solarstrike** [comment]
@Adaptivity I just merged it in my fork.

**Pull request closed without merging**
